version: "3.9"
services:
  pgdb:
    image: postgres
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - ${DB_PORT}:5432
    networks:
      - pgnet
    volumes:
      - pgdata:/var/lib/postgresql/data
  pgadmin:
    image: dpage/pgadmin4
    ports:
      - ${PGADMIN_PORT}:80
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    networks:
      - pgnet
    volumes:
      - pgadmindata:/var/lib/postgresql/data
  mongo:
    image: mongo
    # environment:
    #   MONGO_INITDB_ROOT_USERNAME: ${MONGO_USERNAME}
    #   MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
    networks:
      - mongonet
    volumes:
      - mongodata:/data/db

  mongo-express:
    image: mongo-express
    ports:
      - ${MONGO_EXPRESS_PORT}:8081
    # environment:
    #   ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_USERNAME}
    #   ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_PASSWORD}
    #   ME_CONFIG_MONGODB_URL: mongodb://${MONGO_USERNAME}:${MONGO_PASSWORD}@mongo:27017/
    networks:
      - mongonet
    volumes:
      - mongoexpressdata:/var/lib/postgresql/data
    depends_on:
      - mongo
networks: 
  pgnet:
    driver: bridge
  mongonet:
    driver: bridge
volumes: 
  pgdata:
  pgadmindata:
  mongodata:
  mongoexpressdata: